//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class irixi_mfg_module_Entities : DbContext
    {
        public irixi_mfg_module_Entities()
            : base("name=irixi_mfg_module_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<definition_department> definition_department { get; set; }
        public virtual DbSet<definition_role> definition_role { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<product_Info> product_Info { get; set; }
        public virtual DbSet<sn_changelog> sn_changelog { get; set; }
        public virtual DbSet<spec> spec { get; set; }
        public virtual DbSet<spec_baseinfo> spec_baseinfo { get; set; }
        public virtual DbSet<test_result> test_result { get; set; }
        public virtual DbSet<test_result_baseinfo> test_result_baseinfo { get; set; }
        public virtual DbSet<test_result_extended> test_result_extended { get; set; }
        public virtual DbSet<spec_extended> spec_extended { get; set; }
    }
}
