//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class sn_changelog
    {
        public int id { get; set; }
        public string old_sn { get; set; }
        public string new_sn { get; set; }
        public int operator_id { get; set; }
        public string station { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual user user { get; set; }
    }
}
