//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class spec
    {
        public int baseinfo_id { get; set; }
        public double volt__min { get; set; }
        public double volt__max { get; set; }
        public double icc__min { get; set; }
        public double icc__max { get; set; }
        public double consumption__min { get; set; }
        public double consumption__max { get; set; }
        public double tx_lop__min { get; set; }
        public double tx_lop__max { get; set; }
        public double er__min { get; set; }
        public double er__max { get; set; }
        public double emm__min { get; set; }
        public double emm__max { get; set; }
        public double crossing__min { get; set; }
        public double crossing__max { get; set; }
        public double jitter_pp__min { get; set; }
        public double jitter_pp__max { get; set; }
        public double jitter_rms__min { get; set; }
        public double jitter_rms__max { get; set; }
        public double tx_rise_time__min { get; set; }
        public double tx_rise_time__max { get; set; }
        public double tx_fall_time__min { get; set; }
        public double tx_fall_time__max { get; set; }
        public double tx_dis_lop__min { get; set; }
        public double tx_dis_lop__max { get; set; }
        public double sens_e12__min { get; set; }
        public double sens_e12__max { get; set; }
        public double sens_oma_e12__min { get; set; }
        public double sens_oma_e12__max { get; set; }
        public double sens_5e5__min { get; set; }
        public double sens_5e5__max { get; set; }
        public double sens_oma_5e5__min { get; set; }
        public double sens_oma_5e5__max { get; set; }
        public double losa__min { get; set; }
        public double losa__max { get; set; }
        public double losd__min { get; set; }
        public double losd__max { get; set; }
        public double losh__min { get; set; }
        public double losh__max { get; set; }
        public double dut_temps__min { get; set; }
        public double dut_temps__max { get; set; }
        public double ddm_temps__min { get; set; }
        public double ddm_temps__max { get; set; }
        public double ddm_temps_error__min { get; set; }
        public double ddm_temps_error__max { get; set; }
        public double ddm_tx_power__min { get; set; }
        public double ddm_tx_power__max { get; set; }
        public double ddm_tx_power_error__min { get; set; }
        public double ddm_tx_power_error__max { get; set; }
        public double ddm_rx_power__min { get; set; }
        public double ddm_rx_power__max { get; set; }
        public double ddm_rx_power_error__min { get; set; }
        public double ddm_rx_power_error__max { get; set; }
        public double ddm_bias__min { get; set; }
        public double ddm_bias__max { get; set; }
        public double ddm_vcc__min { get; set; }
        public double ddm_vcc__max { get; set; }
        public double ddm_vcc_error__min { get; set; }
        public double ddm_vcc_error__max { get; set; }
        public double tx_oma__min { get; set; }
        public double tx_oma__max { get; set; }
        public double overload__min { get; set; }
        public double overload__max { get; set; }
    
        public virtual spec_baseinfo spec_baseinfo { get; set; }
    }
}
