//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class spec_baseinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spec_baseinfo()
        {
            this.test_result_baseinfo = new HashSet<test_result_baseinfo>();
        }
    
        public int id { get; set; }
        public string pn { get; set; }
        public decimal temp { get; set; }
        public int verson { get; set; }
        public int operator_id { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual spec spec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_result_baseinfo> test_result_baseinfo { get; set; }
        public virtual spec_extended spec_extended { get; set; }
    }
}
