//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class spec_extended
    {
        public int baseinfo_id { get; set; }
        public double tdp__min { get; set; }
        public double tdp__max { get; set; }
        public double center_wl__min { get; set; }
        public double center_wl__max { get; set; }
        public double smsr__min { get; set; }
        public double smsr__max { get; set; }
    
        public virtual spec_baseinfo spec_baseinfo { get; set; }
    }
}
